services:
    nginx:
        container_name: nginx-container
        image: nginx
        build: ./requirements/nginx
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - wp-data:/var/www/html
            - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./requirements/nginx/ssl:/etc/nginx/ssl
        depends_on:
            - wordpress
        networks:
            - inception
        restart: always

    wordpress:
        container_name: wordpress-container
        image: wordpress
        build: ./requirements/wordpress/
        depends_on:
            - mariadb
        ports:
            - "9000"
        volumes:
            - wp-data:/var/www/html
        env_file:
            - .env
        networks:
            - inception
        restart: always

    mariadb:
        container_name: mariadb-container
        tty: true
        build: ./requirements/mariadb
        image: mariadb
        volumes:
            - db-data:/var/lib/mysql
        env_file:
            - .env
        networks:
            - inception
        restart: always
        ports:
            - "3306:3306"

volumes:
    wp-data:
        driver: local
        driver_opts:
            # device: /Users/user/data/wordpress
            device: "/Users/user/Inception/srcs/requirements/wordpress"
            o: bind
            type: none

    db-data:
        driver: local
        driver_opts:
            # device: "/Users/user/data/mariadb"
            device: "/Users/user/Inception/srcs/requirements/mariadb"
            o: "bind"
            type: "none"
networks:
    inception:
        driver: bridge