services:
    nginx:
        container_name: nginx-container
        image: nginx
        build: ./requirements/nginx
        ports:
            - "443:443"
        volumes:
            - ./requirements/nginx/html:/usr/share/nginx/html
            - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./requirements/nginx/ssl:/etc/nginx/ssl
            - ./logs/nginx:/var/log/nginx
        depends_on:
            - wordpress
        networks:
            - frontend
        restart: always

    wordpress:
        container_name: wordpress-container
        image: wordpress
        build: ./requirements/wordpress/
        depends_on:
            - mariadb
        ports:
            - "80:80"
        volumes:
            - wp-data:/var/www/html
        env_file:
            - .env
        networks:
            - frontend
            - backend
        restart: always

    mariadb:
        container_name: mariadb-container
        tty: true
        build: ./requirements/mariadb
        image: mariadb
        volumes:
            - db-data:/var/lib/mysql
        env_file:
            - .env
        networks:
            - backend
        restart: always
        ports:
            - "3306:3306"

volumes:
    wp-data:
        driver: local
        driver_opts:
            device: /Users/user/42Tokyo/Inception/srcs/requirements/wordpress
            o: bind
            type: none

    db-data:
        driver: local
        driver_opts:
            device: "/Users/user/42Tokyo/Inception/srcs/requirements/mariadb"
            o: "bind"
            type: "none"
networks:
    frontend:
    backend:
        driver: bridge